### ISSUE TITLE
linux dependency

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/cygl#2]
sudo-apt-get install libglew-dev

should be

sudo apt-get install libglew-dev

:)

**Comment by cpicanco** [comment]
should include cython as dependency too

**Comment by cpicanco** [comment]
trying with pip install cython

**Comment by cpicanco** [comment]
fail
trying with sudo pip install cython

**Comment by cpicanco** [comment]
cython successfully installed
trying the build command

sudo python setup.py install

fail

> shader.pyx:1:0: 'cygl-master.shader' is not a valid module name
> Traceback (most recent call last):
>   File "setup.py", line 69, in <module>
>     ext_modules = cythonize(extensions)
>   File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 865, in cythonize
>     cythonize_one(*args[1:])
>   File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 985, in cythonize_one
>    raise CompileError(None, pyx_file)
> Cython.Compiler.Errors.CompileError: shader.pyx

**Comment by cpicanco** [comment]
changing the name of the folder from cygl-master to cygl solves... (should you workaround that?)

cygl successful installed
